### ISSUE TITLE
cubicleA not defined (EHV - DC lines)

### ISSUE THREAD

**Issue by TobiasRitschel** [ie3-institute/simBench2PowerFactory#2]
Hello, when using PowerFactory, I get the error

Traceback (most recent call last):
  File "<string>", line 27, in <module>
  File "C:\Users\...\simBench2PowerFactory-main\simBench2PowerFactory\Simbench2PowerFactory.py", line 578, in <module>
    newdcline = pfoc.createDCLine(grid, row, cubicleA, cubicleB, dclinetype)
NameError: name 'cubicleA' is not defined

when trying to import the time series data in .csv format for the 1-EHV-mixed--2-no_sw grid (I've omitted part of the path).

Do you know what might be causing this?

**Comment by johanneshiry** [comment]
Hi @TobiasRitschel,
thanks for your request. We informed the person who wrote the script about your issue. However, in order to reproduce the issue it would be helpful if you could provide the full data set you're trying to convert to PF.

This issue looks like the `Line.csv` file is missing an column entry for a `nodeB`.  Have you modified the original simbench dataset?

**Comment by TobiasRitschel** [comment]
Hi @johanneshiry, thank you for the fast reply.

I am working with the 1-EHV-mixed--2-no_sw.csv dataset
http://141.51.193.167/simbench/gui/usecase/download/?simbench_code=1-EHV-mixed--2-no_sw&format=csv

I haven't modified the dataset, and to me, it doesn't look like the nodeB entry is missing for the DC lines.

**Comment by dzanansarajlic** [comment]
Hi @TobiasRitschel,
unfortunately I was not able to reproduce the error.
Importing the dataset 1-EHV-mixed--2-no_sw by using the simBench2PowerFactory-converter worked without errors.

Since you haven't modified the dataset, I would suggest to use directly the .pfd file of that model and import it to PowerFactory (see: http://141.51.193.167/simbench/gui/usecase/download/?simbench_code=1-EHV-mixed--2-no_sw&format=powerfactory).

The .pfd model is already set up so that it can be used in PowerFactory. What must be adjusted, however, is that the path of the time series in the PowerFactory project must refer to the corresponding *Profile.csv files (e.g. for the loads the path must lead to LoadProfile.csv). The path adjustment in PowerFactory can be done via the Data Manager under "Characteristics and scaling factors". Afterwards, the time series must be activated in the PowerFactory project.

**Comment by TobiasRitschel** [comment]
Thank you for checking. I will try once more starting with .pfd model.

For now, I will close the issue since it is not reproducible.

Thanks again.
